// Copyright (c) 2014 M-Way Solutions GmbH
// http://github.com/mwaylabs/The-M-Project/blob/absinthe/MIT-LICENSE.txt

////////////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE - it is generated by grunt
////////////////////////////////////////////////////////////////

M.ThemeVars = {
    _vars: {
    "default": {
        "blue": "#1092d3",
        "lightblue": "#58b3e0",
        "darkblue": "#0e7cb4",
        "purple": "#6c64ff",
        "lightpurple": "#9893ff",
        "darkpurple": "#5c55d9",
        "green": "#2dcca2",
        "lightgreen": "#6cdbbe",
        "darkgreen": "#26ae8a",
        "red": "#ed253d",
        "lightred": "#f26778",
        "darkred": "#ca1f34",
        "orange": "#f45b42",
        "lightorange": "#f78d7b",
        "darkorange": "#d04d38",
        "yellow": "#eab13a",
        "lightyellow": "#f0c975",
        "darkyellow": "#d99731",
        "grey": "#c3c3c3",
        "lightgrey": "#d5d5d5",
        "darkgrey": "#a6a6a6",
        "black": "#000000",
        "white": "#FFFFFF",
        "darkwhite": "#F2F2F2",
        "debug-1": "#02ccb9",
        "debug-2": "#00cc09",
        "debug-3": "#cc3500",
        "debug-4": "#cc008d",
        "debug-5": "#9f00cc",
        "debug-6": "#4f00cc",
        "debug-7": "#003fcc",
        "debug-8": "#0073cc",
        "grid-columns": "12",
        "grid-gutter-width": "30px",
        "lightenPercentage": "15%",
        "lightenPercentageLight": "5%",
        "m-button-icon-only-width": "50px",
        "m-button-border-width": "1px",
        "m-button-border-color": "#1092d3",
        "m-button-text-color": "#1092d3",
        "m-button-border-radius": "4px",
        "m-button-border-style": "solid",
        "m-button-padding-bottom": "10px",
        "m-button-padding-top": "10px",
        "m-button-padding-left-right": "10px",
        "m-button-padding": "10px 10px 10px 10px",
        "m-button-primary-border-color": "#6c64ff",
        "m-button-primary-text-color": "#6c64ff",
        "m-button-primary-background-color": "#FFFFFF",
        "m-button-success-border-color": "#2dcca2",
        "m-button-success-text-color": "#2dcca2",
        "m-button-success-background-color": "#FFFFFF",
        "m-button-error-border-color": "#ed253d",
        "m-button-error-text-color": "#ed253d",
        "m-button-error-background-color": "#FFFFFF",
        "m-button-warning-border-color": "#f45b42",
        "m-button-warning-text-color": "#f45b42",
        "m-button-warning-background-color": "#FFFFFF",
        "m-button-info-border-color": "#eab13a",
        "m-button-info-text-color": "#eab13a",
        "m-button-info-background-color": "#FFFFFF",
        "m-button-fuzzy-border-color": "#c3c3c3",
        "m-button-fuzzy-text-color": "#c3c3c3",
        "m-button-fuzzy-background-color": "#FFFFFF",
        "strong": "bold",
        "normal": "normal",
        "weak": "lighter",
        "form-border-width": "1px",
        "form-border-color": "#1092d3",
        "form-border-style": "solid",
        "form-element-border": "1px solid #1092d3",
        "textfield-icon-padding": "30px",
        "textfield-icon-x-position": "4px",
        "textfield-icon-y-position": "14px",
        "textfield-icon-font-size": "2.2rem",
        "textfield-padding": "6px",
        "m-primary-color": "#1092d3",
        "m-primary-text-color": "#000000",
        "m-primary-border-color": "#58b3e0",
        "m-primary-active-color": "#0e7cb4",
        "m-primary-active-text-color": "#FFFFFF",
        "tablayout-menu-height": "50px",
        "tablayout-menu-button-padding": "13px 0 0 0",
        "tablayout-menu-scroll-button-width": "200px",
        "switch-header-content-padding": "4px 0 0 0",
        "header-top": "4px",
        "m-header-icon-only-font-size": "2.4rem",
        "m-primary-font-family": "\"HelveticaNeue-Light\", \"Helvetica Neue Light\", \"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif",
        "m-primary-font-weight": "300",
        "m-primary-font-size": "1.6rem",
        "m-primary-calc-font-size": "16px",
        "m-primary-line-height": "2.2rem",
        "m-primary-font-color": "#000000",
        "m-primary-margin-top": "10px",
        "m-primary-margin-bottom": "20px",
        "modal-backdrop-background-color": "#000000",
        "content-padding": "15px",
        "m-primary-disabled-color": "#d5d5d5",
        "m-primary-disabled-text-color": "#c3c3c3",
        "selection-color": "#c3c3c3",
        "selection-checked-color": "#1092d3",
        "m-list-item-color": "#2dcca2",
        "m-stencil-text-shadow": "rgba(255, 255, 255, 0.5) 0px 3px 3px",
        "m-menu-view-width": "200px",
        "m-menu-view-device-swipe-listener-width": "20px",
        "m-menu-view-transition-width": "200px - 20px",
        "m-menu-transition": "500ms"
    },
    "android_dark": {
        "m-primary-color": "#669900",
        "m-primary-border-color": "#669900",
        "m-primary-active-color": "#99CC00"
    },
    "android_light": {
        "m-primary-color": "#669900",
        "m-primary-border-color": "#669900",
        "m-primary-active-color": "#99CC00"
    },
    "ios": {
        "blue": "#59C8FA",
        "lightblue": "#46b8da",
        "darkblue": "#007AFF",
        "green": "#4BD964",
        "red": "#FF3B30",
        "lightred": "#FF2D55",
        "grey": "#8E8E93",
        "m-primary-font-family": "-apple-system-font, \"HelveticaNeue-Light\", \"Helvetica Neue Light\", \"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif",
        "lightenPercentage": "25%",
        "textfield-icon-y-position": "13px",
        "m-primary-active-color": "$lightgrey",
        "m-primary-active-text-color": "#007AFF",
        "tablayout-menu-height": "50px",
        "tablayout-menu-scroll-button-width": "140px",
        "selection-checked-color": "#59C8FA",
        "m-button-padding-bottom": "10px",
        "m-button-padding": "$m-button-padding-top $m-button-padding-left-right 10px $m-button-padding-left-right-top $m-button-padding-top $m-button-padding-left-right 10px $m-button-padding-left-right-left-right 10px $m-button-padding-top $m-button-padding-left-right 10px $m-button-padding-left-right-left-right"
    }
},
    get: function (name, theme) {
        var theme = theme || M.Environment.device.os;

        var result = this._vars[theme] ? this._vars[theme][name] : false;
        if (!result && theme != M.ThemeVars.CONST.DEFAULT) {
            result = this._vars[M.ThemeVars.CONST.DEFAULT][name];
        }
        if (!result) {
            console.log('Can not find varibale "' + name + '".');
        }
        return result;
    }
}

M.ThemeVars.CONST = {
    IOS: 'ios',
    ANDROID_DARK: 'android_dark',
    ANDROID_LIGHT: 'android_light',
    ANDROID: 'android_dark',
    DEFAULT: 'default'
}