// ==========================================================================
// Project:   The M-Project - Mobile HTML5 Application Framework
// Copyright: (c) 2010 M-Way Solutions GmbH. All rights reserved.
// Creator:   Sebastian
// Date:      25.11.2010
// License:   Dual licensed under the MIT or GPL Version 2 licenses.
//            http://github.com/mwaylabs/The-M-Project/blob/master/MIT-LICENSE
//            http://github.com/mwaylabs/The-M-Project/blob/master/GPL-LICENSE
// ==========================================================================

Contacts.Contact = M.Model.create({
    __name__: 'Contact', // is generated by generator

    firstName: M.Model.attr('String',{
        isRequired:YES
    }),

    lastName: M.Model.attr('String', {
        isRequired:YES
    }),

    /*company: M.Model.attr('String', {
        isRequired:NO
    }),

    street: M.Model.attr('String', {
        isRequired:NO
    }),*/

    zip: M.Model.attr('Integer', {
        isRequired:NO,
        validators: [M.NumberValidator]//, M.NotMinusValidator]
    })

    /*city: M.Model.attr('String', {
        isRequired:NO
    }),

    mobile: M.Model.attr('String', {
        isRequired: NO,
        validators: [M.PhoneValidator]
    }),

    email: M.Model.attr('String', {
        isRequired: NO,
        validators: [M.EmailValidator]
    }),

    homepage: M.Model.attr('String', {
        isRequired: NO,
        validators: [M.UrlValidator]
    }),

    birthday: M.Model.attr('String', {
        isRequired: NO  
    }),

    notes: M.Model.attr('Text', {
        isRequired: NO
    })*/

}, M.WebSqlProvider.configure({
    dbName: 'contacts_db'
}));