// ==========================================================================
// Project:   The M-Project - Mobile HTML5 Application Framework
// Copyright: (c) 2010 M-Way Solutions GmbH. All rights reserved.
// Creator:   Sebastian
// Date:      09.12.2010
// License:   Dual licensed under the MIT or GPL Version 2 licenses.
//            http://github.com/mwaylabs/The-M-Project/blob/master/MIT-LICENSE
//            http://github.com/mwaylabs/The-M-Project/blob/master/GPL-LICENSE
// ==========================================================================

CRMLight.Activity = M.Model.create({
    __name__: 'Activity', // is generated by generator

    /* Properties on basis of list in "Fachkonzept", page 9 */

    gvl: M.Model.attr('String', {   // gvl is blackberry client
       isRequired:NO
    }),

    beginDate: M.Model.attr('Date', {   // begindate
        isRequired: NO,
        validators: [M.DateValidator]
    }),

    endDate: M.Model.attr('Date', {     // enddate
        isRequired: NO,
        validators: [M.DateValidator]
    }),

    createDate: M.Model.attr('String', {  // createdate
        isRequired: NO    
    }),

    modifyDate: M.Model.attr('String', {  // modifydate
        isRequired: NO
    }),

    category: M.Model.attr('String', {  // category
        isRequired: NO
    }),

    description: M.Model.attr('Text', { // desc
        isRequired: NO
    }),

    processType: M.Model.attr('String', {   // proctype
        isRequired: NO
    }),

    status: M.Model.attr('String', {    // status
        isRequired: NO
    }),

    activityReason: M.Model.attr('String', {    // actreason
        isRequired: NO
    }),

    goal: M.Model.attr('String', {  // 
        isRequired: NO
    }),

    result: M.Model.attr('String', { // result
        isRequired: NO
    }),

    resultReason: M.Model.attr('String', { // ?
        isRequired: NO
    }),

    text: M.Model.attr('Text', {    // appendtext
        isRequired: NO
    }),

    // maybe changed to link to a contact model
    responsiblePerson: M.Model.attr('String', { // responname  
        isRequired: NO
    }),

    isRead: M.Model.attr('Boolean', {   // read
        isRequired: NO
    }),

    customerId: M.Model.attr('Integer', {   // customer
        isRequired: NO,
        validators: [M.NumberValidator]
    })

    // hasOne: Customers

}, M.WebSqlProvider.configure({
    dbName: 'crm_light_db'
}));